$(document).ready(function(){
    $(".dropbtn").click(function(){
        $(".para1").toggle();
    });
});
$(document).ready(function(){
    $(".dbtn").click(function(){
        $(".para2").toggle();
    });
});